# Generated by Django 3.2.6 on 2021-08-30 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('link', models.URLField(max_length=500)),
                ('company', models.CharField(max_length=300)),
                ('skills', models.CharField(blank=True, max_length=1000, null=True)),
                ('initial_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('tags', models.ManyToManyField(to='main_app.Tag')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('jobtitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.jobtitle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True)),
                ('first_name', models.CharField(blank=True, max_length=35)),
                ('last_name', models.CharField(default='Enter', max_length=35)),
                ('pronoun', models.CharField(default='Enter', max_length=50)),
                ('about_me', models.TextField(default='Enter', max_length=500)),
                ('state_location', models.CharField(default='Enter', max_length=100)),
                ('city_location', models.CharField(default='Enter', max_length=100)),
                ('joblist', models.ManyToManyField(to='main_app.JobTitle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
