# Generated by Django 3.2.6 on 2021-08-19 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_jobtitle_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('tag', models.CharField(choices=[('1', 'Job is Cool'), ('2', 'Job is Aight'), ('3', 'Technical Interview...thats tuff'), ('4', '&#128175;'), ('5', '')], default='1', max_length=1)),
                ('jobtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.jobtitle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
