# Generated by Django 3.2.6 on 2021-08-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tag',
            field=models.CharField(choices=[('Job is Cool', 'Job is Cool'), ('Job is Aight', 'Job is Aight'), ('Technical Interview...thats tuff', 'Technical Interview...thats tuff'), ('&#128175;', '&#128175;')], default='Job is Cool', max_length=200),
        ),
    ]
