# Generated by Django 3.2.6 on 2021-08-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tag',
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='tags',
            field=models.ManyToManyField(to='main_app.Tag'),
        ),
    ]
