# Generated by Django 3.2.6 on 2021-08-23 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0013_alter_applicant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='user',
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
