# Generated by Django 3.2.6 on 2021-08-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210823_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
