# Generated by Django 3.2.6 on 2021-08-24 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0017_remove_tag_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
