# Generated by Django 3.2.6 on 2021-08-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_tag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
