# Generated by Django 3.2.6 on 2021-08-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_jobtitle_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='initial_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
