# Generated by Django 3.2.6 on 2021-08-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20210824_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='initial_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='skills',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
