# Generated by Django 3.2.6 on 2021-08-27 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20210826_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='about_me',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='city_location',
            field=models.CharField(default='los angeles', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(default='test', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(default='tester', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='pronoun',
            field=models.CharField(default='they', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='state_location',
            field=models.CharField(default='ca', max_length=100),
            preserve_default=False,
        ),
    ]
