# Generated by Django 3.2.6 on 2021-08-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20210826_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='about_me',
            field=models.TextField(default='Enter', max_length=500),
        ),
        migrations.AddField(
            model_name='applicant',
            name='city_location',
            field=models.CharField(default='Enter', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(default='Enter', max_length=35),
        ),
        migrations.AddField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(default='Enter', max_length=35),
        ),
        migrations.AddField(
            model_name='applicant',
            name='pronoun',
            field=models.CharField(default='Enter', max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='state_location',
            field=models.CharField(default='Enter', max_length=100),
        ),
    ]
