# Generated by Django 3.2.6 on 2021-08-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_applicant_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='about_me',
            field=models.TextField(default='Enter', max_length=500),
        ),
    ]
