# Generated by Django 3.2.6 on 2021-08-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_applicant_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
